#!/usr/bin/env python3
# 입력 생성기

import random

# 파라미터
SEED = 0
COUNT = 16

# 재현 가능하도록 랜덤시드 고정
random.seed(SEED)
rand = lambda n: [
    random.randrange(1000000) if random.random() >= 0.2 else 0 for _ in range(n)
]

print(COUNT)
print('\n'.join(
    ' '.join(str(elem) for elem in rand(i) + [0] + rand(COUNT - 1 - i))
    for i in range(COUNT)
))
