#!/usr/bin/env python3
from subprocess import run
from sys import exit
from random import randint

def test(A, B) -> bool:
    input = b'%d %d' % (A, B)
    a = run(['python3', 'solution.py'], input=input, capture_output=True)
    b = run(['./solution'], input=input, capture_output=True)
    if a.stdout == b.stdout:
        print('.', end='', flush=True)
    else:
        print(f'{a.stdout} != {b.stdout}')
        exit(-1)

test(10000, 500)

for _ in range(10):
    test(randint(1, 1000), randint(1, 1000))

test(10**1000, 10**1000)

NINES = 10**10000 - 1
while True:
    test(randint(1, NINES), randint(1, NINES))
