#!/usr/bin/env python
from random import sample
N = 500000

print(N)
print(' '.join(map(str, sample(range(-10000000, 10000001), N))))
print(N)
print(' '.join(map(str, sample(range(-10000000, 10000001), N))))
