#!/usr/bin/env python3
from sys import argv
from random import Random

if __name__ == '__main__':
    count = int(argv[1]) if len(argv) > 1 else 50
    seed = int(argv[2]) if len(argv) > 2 else 0

    rng = Random(seed)
    print(count)
    print(' '.join(str(rng.randrange(101)) for _ in range(count)))
    print(' '.join(str(rng.randrange(101)) for _ in range(count)))
