#!/usr/bin/env python3
from sys import argv
from random import Random

def dummy_input(count: int, seed: int):
    rng = Random(seed)
    yield from (
        rng.randrange(1_000_000) for _ in range(count)
    )

if __name__ == '__main__':
    # 파라미터
    count = int(argv[1]) if len(argv) > 1 else 10000
    seed = int(argv[2]) if len(argv) > 2 else 0

    # 실행
    for val in dummy_input(count, seed):
        print(val)
