#!/usr/bin/env python3
from sys import argv, stdout
from random import seed, randrange

# 파라미터
SEED = 0
COUNT = int(argv[1]) if len(argv) > 1 else 1_000_000

seed(SEED)
rand = lambda: str(randrange(1, 1_000_001))

print(COUNT)
stdout.write(rand())
for _ in range(1, COUNT):
    stdout.write(' ' + rand())
