#!/usr/bin/env python3
# https://www.acmicpc.net/problem/7568
from dataclasses import dataclass

# 데이터클래스
# Reference: https://docs.python.org/3/library/dataclasses.html
@dataclass
class Person:
    id: int
    weight: int
    height: int

    # '<' 연산자 정의
    # Reference: https://docs.python.org/3/reference/datamodel.html#object.__lt__
    def __lt__(self, other) -> bool:
        return self.weight < other.weight and self.height < other.height

count = int(input())
people = [Person(id, *map(int, input().split())) for id in range(count)]
print(' '.join(
    str(sum(1 for e in people if person < e) + 1)
    for person in people
))
