#!/usr/bin/env python
from sys import argv
from random import seed, choice

seed(argv[1])

T = 1
print(T)
for _ in range(T):
    x1 = choice(range(-1000, 1001))
    y1 = choice(range(-1000, 1001))
    x2 = choice(range(-1000, 1001))
    y2 = choice(range(-1000, 1001))
    n = choice(range(1, 50))
    print(f'{x1} {y1} {x2} {y2}\n{n}')
    for _ in range(n):
        cx = choice(range(-1000, 1001))
        cy = choice(range(-1000, 1001))
        r = choice(range(1, 1000))
        print(f'{cx} {cy} {r}')
