#!/usr/bin/env python3

# Reference:
#   https://www.acmicpc.net/problem/2839

TABLE = [0, 2, 4, 1, 3]

def foo(number):
    count_3 = TABLE[number % 5]
    count_5 = (number - 3*count_3)//5
    return count_3 + count_5 if count_5 >= 0 else -1

assert foo(18) == 4
assert foo(4) == -1
assert foo(6) == 2
assert foo(9) == 3
assert foo(11) == 3

print(foo(int(input())))
