#!/usr/bin/env python3

# Reference:
#   https://www.acmicpc.net/problem/2839

def foo(number):
    count_5 = number // 5

    while (number - 5*count_5) % 3 != 0 and count_5 >= 0:
        count_5 -= 1

    count_3 = (number - 5*count_5)//3

    return count_3 + count_5 if count_5 >= 0 else -1

assert foo(18) == 4
assert foo(4) == -1
assert foo(6) == 2
assert foo(9) == 3
assert foo(11) == 3

print(foo(int(input())))
